### ISSUE TITLE
feature request: write gridOrient file

### ISSUE THREAD

**Issue by mattkleonard** [catalystneuro/ecogVIS#116]
Can we write out something like an `ECXXX_gridOrient.mat` file that contains a 2D matrix that's used to plot ERPs in ecogVIS?

**Comment by emilyps14** [comment]
The simplest way to do this would be to have the user rotate/flip the grid until it's in the right configuration, then have an export function that outputs the matrix of channel numbers. 

But also, this could be a good opportunity to improve how ecogvis makes the grids themselves:
1. Using the x,y,z coordinates of the electrodes to figure out the row definitions rather than assuming they are in blocks of 16
2.  When possible, using the x,y,z to guess about the best orientation prior to plotting

**Comment by mattkleonard** [comment]
And actually, since this is something that's basically always needed for any grid case, I wonder if we should have this be part of the imaging pipeline, rather than preprocessing. i.e., so this file doesn't have to be generated by each user.

**Comment by emilyps14** [comment]
Good point -- if it becomes a part of the imaging pipeline then we can make use of it in the ERP plotting in ecogvis (instead of the changes above)
