### ISSUE TITLE
Copying of changlab_to_nwb code into this repo

### ISSUE THREAD

**Issue by jrliu95** [catalystneuro/ecogVIS#91]
@luiztauffer  I see that on the `htk_loader` branch, some of the code that I gave you guys is copied in here. Some of that might be confusing because a lot of it is outdated or is specific to our private `changlab_to_nwb` repo (so it's code that won't even run). 

For example, `ecogvis.functions.tdt_to_nwb.chang2nwb` hosts a lot of outdated code but also the updated electrodes table function. I think it would be best to remove everything that is not being used and create a specific file to contain functions that are being used like `elecs_to_electrode_table`.

**Comment by luiztauffer** [comment]
Hi @jrliu95, I was refraining from removing anything that wasn't being substituted by my own version, since I don't know how much of that you guys might end up using in the future, so I thought of leaving as reference
But I agree with you, all that unused code might confuse more than help. 
I'll clean it up

**Comment by luiztauffer** [comment]
much cleaner now!

**Comment by jrliu95** [comment]
Looks much better, thanks!
